-- Table des rôles
CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- Table des utilisateurs
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email    VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    role_id  BIGINT REFERENCES roles (id) ON DELETE CASCADE ON UPDATE NO ACTION,
    provider VARCHAR,
    enabled  BOOL
);


-- Table pour associer un utilisateur, un Dinatoon et une liste
CREATE TABLE IF NOT EXISTS user_dinatoons
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
    dinatoon_id     UUID,
    rating          BIGINT,
    comment         TEXT,
    current_chapter TEXT,
    UNIQUE (user_id, dinatoon_id),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table des catégories
CREATE TABLE IF NOT EXISTS categories
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION
);

-- Table intermédiaire pour la relation ManyToMany entre catégories et Dinatoons
CREATE TABLE IF NOT EXISTS category_dinatoon
(
    category_id    BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    user_dinatoons BIGINT REFERENCES user_dinatoons (id) ON DELETE CASCADE,
    PRIMARY KEY (category_id, user_dinatoons)
);

-- Table des tokens de confirmation
CREATE TABLE IF NOT EXISTS confirmation_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      TEXT,
    user_id    BIGINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
    created_at TIMESTAMP DEFAULT (NOW())
);

-- Index pour optimiser les requêtes
CREATE INDEX idx_user_id ON user_dinatoons (user_id);
CREATE INDEX idx_dinatoon_id ON user_dinatoons (dinatoon_id);
CREATE INDEX idx_category_user_id ON categories (user_id);
ALTER TABLE user_dinatoons
    ADD CONSTRAINT unique_dinatoon UNIQUE (dinatoon_id);